apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.oauthServerName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.oauthServerName }}
data:
  OAUTH_CLIENT_ID: {{ .Values.oauth_client_id | quote }}
  OAUTH_CLIENT_SECRET: {{ .Values.oauth_client_secret | quote }}
