name: marketing-connector
version: 0.1.0
description: "Enables the preview integration of SAP Marketing Cloud. It is not recommended for production scenarios."
id: faebbe18-0a84-11e9-ab14-d663bd873d92
displayName: "[Preview] SAP Marketing Cloud - Connector"
tags: marketing,connector
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription:  "Integrates an SAP Marketing Cloud instance in a preview mode by registering its ODATA services and Event catalog in an existing Application and activates Event sending based on MQTT. It is not recommended for production scenarios."
documentationURL: https://storage.googleapis.com/faros-stage-base-xf-bundles/installation/marketing.html
imageURL: https://storage.googleapis.com/faros-stage-base-xf-bundles/icons/marketing-connector.svg
bindable: false
provisionOnlyOnce: true
