name: commerce-mock
version: 0.1.0
description: "Lightweight substitute of SAP Commerce Cloud based on APIs only. It is not recommended for production scenarios."
id: faebbe18-0a84-11e9-ab14-d663bd873d98
displayName: "[Preview] SAP Commerce Cloud - Mock"
tags: commerce,mock
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription:  "Lightweight substitute of SAP Commerce Cloud based on APIs only. It is recommended for production scenarios."
documentationURL: https://github.com/SAP/xf-application-mocks/tree/master/commerce-mock
imageURL: https://storage.googleapis.com/faros-stage-base-xf-bundles/icons/commerce-mock.svg
bindable: false
provisionOnlyOnce: true
