apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    app: {{ template "bundle.fullname" . }}
  name: {{ template "bundle.fullname" . }}
spec:
  hostname: commerce-{{ .Release.Namespace }}
  service:
    name: {{ template "bundle.fullname" . }}
    port: 10000