apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
    spec:
      containers:
      - image: eu.gcr.io/kyma-project/xf-application-mocks/commerce-mock:latest
        imagePullPolicy: Always
        name: {{ template "bundle.fullname" . }}
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  ports:
  - name: http
    port: 10000
  selector:
    app: {{ template "bundle.fullname" . }}
---
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  labels:
    app: {{ template "bundle.fullname" . }}
  name: {{ template "bundle.fullname" . }}
spec:
  hostname: commerce-{{ .Release.Namespace }}
  service:
    name: {{ template "bundle.fullname" . }}
    port: 10000
---
apiVersion: cms.kyma-project.io/v1alpha1
kind: DocsTopic
metadata:
  name: commerce-mock
  labels:
    cms.kyma-project.io/view-context: service-catalog
spec:
  displayName: Commerce Mock
  description: "Commerce Mock documentation"
  sources:
    - type: markdown
      name: markdown-commerce
      mode: single
      url: https://github.com/SAP/xf-addons/blob/service-documentation/bundles/commerce-mock-0.1.0/Doc.md