docs:
  - template:
      displayName: "litmos-connector-0.1.0"
      description: "SAP Litmos Connector documentation"
      sources:
        - type: markdown
          name: docs
          mode: package
          filter: (docs/(.*?)\.md$)
        - type: openapi
          name: openapi
          mode: package
          filter: docs/litmos-oa3\.json