name: c4c-mock
version: 0.1.0
description: "Lightweight substitute of SAP Cloud for Customer based on APIs only. It is not recommended for production scenarios."
id: faebbe18-0a84-11e9-ab14-d663bd873d93
displayName: "[Preview] SAP Cloud for Customer - Mock"
tags: preview,c4c,mock
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription:  "Lightweight substitute of SAP Cloud for Customer based on APIs only. It is not recommended for production scenarios."
documentationURL: https://github.com/SAP/xf-application-mocks/tree/master/c4c-mock
imageURL: https://raw.githubusercontent.com/SAP/xf-addons/master/icons/c4c-mock.svg
bindable: false
provisionOnlyOnce: true
