apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "bundle.fullname" . }}
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "false"
