name: litmos-connector
version: 0.1.0
description: "Enables the preview integration of SAP Litmos. It is not recommended for production scenarios."
id: faebbe18-0a84-11e5-ab14-d663bd873d97
displayName: "[Preview] SAP Litmos - Connector"
tags: preview,litmos,connector
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Litmos in preview mode by registering its REST APIs in an existing Application and enables consuming the APIs from a lambda or microservice. It is not recommended for production use."
documentationURL: https://support.litmos.com/hc/en-us/articles/227734667
bindable: false
provisionOnlyOnce: true
imageUrl: https://storage.googleapis.com/faros-stage-base-xf-bundles/icons/litmos-connector.png
