name: cds-connector
version: 0.0.1
description: "Enables the preview integration of CDS APIs and Events. It is not recommended for production scenarios."
id: 15ad661a-6e44-4b15-ab78-33a811d06a8b
displayName: "[Preview] SAP Context-Driven Services- Connector"
tags: preview,cds,connector
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription: "Enables extending CDS in preview mode by registering its REST APIs and Events in an existing Application and enables consuming the APIs from a lambda or microservice with trigger from CDS events. It is not recommended for production use."
documentationURL: https://help.sap.com/viewer/product/CONTEXT-DRIVEN_SERVICES/SHIP/en-US
bindable: false
provisionOnlyOnce: true

