apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bundle.fullname" . }}
  labels:
    app: {{ template "bundle.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "bundle.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bundle.fullname" . }}
    spec:
      containers:
      - image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ template "bundle.fullname" . }}
        ports:
        - name: http
          containerPort: 10000
        env:
        - name: DEBUG
          value: "false"
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "100m"
