# Default values for fieldglass-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

apiRegistrationJobName: api-registration-job
apiProxyName: cc-icm-proxy