apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: "SAP"
  PRODUCT_NAME: "SAP Callidus ICM"
  SYSTEM_URL: {{ template "cc_proxy_service" . }}
  APP_KIND: rest-with-apikey
  API_SPECIFICATION_URL: https://raw.githubusercontent.com/SAP/xf-addons/latest/addons/callidus-icm-connector-0.1.0/docs/assets/callidusicm.json
  API_DESCRIPTION: "APIs for SAP Callidus ICM" 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-api
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
  