name: openconnectors-connector
version: 0.1.0
description: "Enables the preview integration of Open Connectors. It is not recommended for production scenarios."
id: 582b010a-ee2e-4dbf-ae61-d087a0f5f2df
displayName: "[Preview] SAP Cloud Platform Open Connectors - Connector"
tags: preview,open connectors,connector
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Cloud Platform Open Connectors in preview mode. Connector Instances are created in SAP Cloud Platform Open Connectors and after installing this connector using your Open Connectors credentials, service instances will be create the corresponding Applications and Services/APIs in Kyma. It is not recommended for production use."
documentationURL: https://storage.googleapis.com/faros-stage-base-xf-bundles/installation/openconnectors.html
imageURL: https://storage.googleapis.com/faros-stage-base-xf-bundles/icons/openconnectors-connector.png
bindable: false
provisionOnlyOnce: true
