docs:
  - template:
      displayName: "c4c-mock-0.1.0"
      description: "SAP Cloud for Customer Mock documentation"
      sources:
        - type: markdown
          name: docs
          mode: package
          filter: (docs/(.*?)\.md$)