name: qualtrics-connector
version: 0.1.0
description: "Enables the preview integration of SAP Qualtrics. It is not recommended for production scenarios."
id: a974f421-9d6d-441e-ab10-0bc31fd9a9dd
displayName: "[Preview] SAP Qualtrics - Connector"
tags: preview,qualtrics,connector
labels: 
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Qualtrics in preview mode by registering its REST APIs in an existing Application and enables consuming the APIs from a lambda or microservice. This connector also creates subscriptions for events in SAP Qualtrics and provides a gateway that allows events to be published to Kyma. It is not recommended for production use."
documentationURL: https://www.qualtrics.com
imageURL: https://rawcdn.githack.com/SAP/xf-addons/master/icons/qualtrics-connector.svg
bindable: false
provisionOnlyOnce: true
