name: callidus-icm-connector
version: 0.1.0
description: "Enables the preview integration of SAP Callidus ICM. It is not recommended for production scenarios."
id: ef0cf2d7-f2ea-4f6f-b815-fdb73fe49bec
displayName: "[Preview] SAP Callidus ICM - Connector"
tags: preview,callidus,icm,connector
labels:
  preview: "true"
providerDisplayName: SAP
longDescription: "Integrates SAP Callidus ICM in preview mode by registering its APIs in an existing Application and enables consuming the APIs from a lambda or microservice. It is not recommended for production use."
documentationURL: https://docs.calliduscloud.com/
bindable: false
provisionOnlyOnce: true
imageUrl: https://raw.githubusercontent.com/SAP/xf-addons/master/icons/calliduscloud.png
