apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: kyma-system
  name: {{ template "bundle.fullname" . }}-{{ .Release.Name }}-event-gw
  labels:
    app: {{ template "bundle.fullname" . }}-event-gw
    prometheus: monitoring #links to kyma prometheus instance
spec:
  jobLabel: "qualtrics-event-gw"
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "bundle.fullname" . }}-event-gw # label selector for service
  endpoints:
    - port: management # port name in service
      path: "/metrics"