apiVersion: v1
kind: ServiceAccount
metadata:
  name: qualtrics-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: {{ template "bundle.fullname" . }}-{{ .Release.Name }}-role
 labels:
   app: {{ template "bundle.fullname" . }}-webhook-registration  
rules:
 - apiGroups: ["*"]
   resources: ["services"]
   verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{ template "bundle.fullname" . }}-{{ .Release.Name }}-rolebinding
 labels:
   app: {{ template "bundle.fullname" . }}-webhook-registration
subjects:
 - kind: User
   name: system:serviceaccount:{{ .Release.Namespace }}:qualtrics-serviceaccount
   apiGroup: rbac.authorization.k8s.io
roleRef:
 kind: ClusterRole
 name: {{ template "bundle.fullname" . }}-{{ .Release.Name }}-role
 apiGroup: rbac.authorization.k8s.io