apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  SYSTEM_URL	: {{ .Values.system_url | quote }}
  BASIC_USER: {{ .Values.basic_user | quote }}
  BASIC_PASSWORD: {{ .Values.basic_password | quote }}
  APPLICATION_NAME: {{ .Values.application_name | quote }}
  PROVIDER_NAME: SAP
  PRODUCT_NAME: SAP Cloud For Customer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}-api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "bundle.fullname" . }}
    component: {{ template "bundle.fullname" . }}-{{ .Values.apiRegistrationJobName }}
data:
  apis.json: |-
    [
      {
        "path": "sap/byd/odata/v1/c4codataapi",
        "name": "OData API",
        "description": "Use the OData API, to query, read, add, update and delete data from and into SAP Cloud for Customer."
      }
    ]

